import { TaskList, AlarmRingtone, Task } from './types';

export const DEFAULT_LISTS: TaskList[] = [
  { id: 'today', name: 'Today', isDefault: true, createdAt: Date.now() },
  { id: 'tomorrow', name: 'Tomorrow', isDefault: true, createdAt: Date.now() },
  { id: 'upcoming', name: 'Upcoming', isDefault: true, createdAt: Date.now() },
  { id: 'overdue', name: 'Overdue', isDefault: true, createdAt: Date.now() },
  { id: 'goals', name: 'Main Goals', isDefault: true, createdAt: Date.now() },
];

export const RINGTONES: AlarmRingtone[] = [
  { id: 'alarm1', name: 'Classic Alarm', file: '/sounds/alarm1.mp3' },
  { id: 'alarm2', name: 'Gentle Chime', file: '/sounds/alarm2.mp3' },
  { id: 'alarm3', name: 'Urgent Beep', file: '/sounds/alarm3.mp3' },
];

export const DEFAULT_TASKS: Omit<Task, 'id' | 'createdAt' | 'completed'>[] = [
  // === TODAY ===
  {
    listId: 'today',
    title: 'Wake up + Fajr',
    notes: '3:45 AM fixed',
    repeat: 'daily',
    startTime: '03:45',
    endTime: '03:55',
    alarm: true,
    ringtone: 'alarm3',
  },
  {
    listId: 'today',
    title: 'BTech Revision',
    notes: 'Morning theory — fresh mind for concepts',
    repeat: 'daily',
    startTime: '03:55',
    endTime: '05:15',
    alarm: false,
  },
  {
    listId: 'today',
    title: 'Full Stack Technology',
    notes: 'Track 1 — JS core, TS, React, Next.js layers',
    repeat: 'daily',
    startTime: '05:15',
    endTime: '06:45',
    alarm: false,
  },
  {
    listId: 'today',
    title: 'Plan the day',
    notes: 'Quick review of targets',
    repeat: 'daily',
    startTime: '06:45',
    endTime: '07:00',
    alarm: false,
  },
  {
    listId: 'today',
    title: 'College',
    notes: 'Try to leave by 4:50 PM',
    repeat: 'daily',
    startTime: '07:00',
    endTime: '16:50',
    alarm: false,
  },
  {
    listId: 'today',
    title: 'Asr + Maghrib Prayers',
    notes: '5:00–6:00 PM',
    repeat: 'daily',
    startTime: '17:00',
    endTime: '18:00',
    alarm: true,
    ringtone: 'alarm2',
  },
  {
    listId: 'today',
    title: 'Workout',
    notes: '6:00–7:00 PM',
    repeat: 'daily',
    startTime: '18:00',
    endTime: '19:00',
    alarm: false,
  },
  {
    listId: 'today',
    title: 'DSA Practice',
    notes: 'Track 2 — linked lists, stacks, trees, DP etc.',
    repeat: 'daily',
    startTime: '19:00',
    endTime: '20:30',
    alarm: true,
    ringtone: 'alarm1',
  },
  {
    listId: 'today',
    title: 'Dinner',
    notes: '8:30–9:00 PM',
    repeat: 'daily',
    startTime: '20:30',
    endTime: '21:00',
    alarm: false,
  },
  {
    listId: 'today',
    title: 'Arabic Practice',
    notes: 'Speaking + vocabulary + pronunciation',
    repeat: 'daily',
    startTime: '21:00',
    endTime: '22:00',
    alarm: true,
    ringtone: 'alarm2',
  },

  // === TOMORROW ===
  {
    listId: 'tomorrow',
    title: 'BTech Revision',
    notes: 'Continue from today',
    repeat: 'daily',
    startTime: '03:55',
    endTime: '05:15',
    alarm: false,
  },
  {
    listId: 'tomorrow',
    title: 'DSA Practice',
    notes: 'Track 2 — next topic',
    repeat: 'daily',
    startTime: '19:00',
    endTime: '20:30',
    alarm: false,
  },

  // === GOALS ===
  {
    listId: 'goals',
    title: 'DecodeSIH Round 2 — AapdaSarthi Build',
    notes: 'Sep 5 at IIIT Delhi. Building phase in progress.',
    repeat: 'once',
    alarm: false,
  },
  {
    listId: 'goals',
    title: 'Finish Interview Mastery Plan',
    notes: 'Phase 0-4. Rebuild PlacementOS from cold. No applications until all 4 exit boxes tick.',
    repeat: 'once',
    alarm: false,
  },
  {
    listId: 'goals',
    title: 'Get 3+ Merged PRs in AsyncAPI',
    notes: 'Priority assignment for Sep microgrant round ($200-$400/issue via PayPal)',
    repeat: 'once',
    alarm: false,
  },
  {
    listId: 'goals',
    title: 'Ship a Product with Real Users',
    notes: 'Build public technical voice. Chronicle AI or TaskManager.',
    repeat: 'once',
    alarm: false,
  },
  {
    listId: 'goals',
    title: 'Apply to SIH Internal — ABESEC',
    notes: 'Deadline Aug 22, 11 PM. Theme 14: Disaster Management.',
    repeat: 'once',
    alarm: false,
  },
];
